import type { Member, PRItem, ActivityItem, StatCard, DailyActivity } from "@/types";

export const STATS: StatCard[] = [
  {
    label: "Total Commits",
    value: "1,284",
    change: "↑ 12% vs last week",
    direction: "up",
    iconColor: "#7c3aed",
    bgColor: "#ede9fe",
  },
  {
    label: "Pull Requests",
    value: "87",
    change: "↑ 8% vs last week",
    direction: "up",
    iconColor: "#059669",
    bgColor: "#d1fae5",
  },
  {
    label: "Code Review Rate",
    value: "94%",
    change: "↓ 2% vs last week",
    direction: "down",
    iconColor: "#d97706",
    bgColor: "#fef3c7",
  },
  {
    label: "Blocked Issues",
    value: "3",
    change: "↑ 1 new blocker",
    direction: "down",
    iconColor: "#dc2626",
    bgColor: "#fee2e2",
  },
];

export const DAILY_ACTIVITY: DailyActivity[] = [
  { day: "Mon", commits: 55,  prs: 30 },
  { day: "Tue", commits: 70,  prs: 40 },
  { day: "Wed", commits: 45,  prs: 25 },
  { day: "Thu", commits: 85,  prs: 55 },
  { day: "Fri", commits: 60,  prs: 35 },
  { day: "Sat", commits: 95,  prs: 65 },
  { day: "Sun", commits: 78,  prs: 48 },
];

export const ACTIVITY_FEED: ActivityItem[] = [
  {
    id: "1",
    initials: "AL",
    name: "Alex",
    action: "merged PR #142 —",
    target: "Auth refactor",
    timeAgo: "2 min ago",
    tag: "Merged",
    avatarColor: "linear-gradient(135deg,#8b5cf6,#6d28d9)",
  },
  {
    id: "2",
    initials: "JK",
    name: "Jordan",
    action: "opened PR #143 —",
    target: "Dashboard UI",
    timeAgo: "15 min ago",
    tag: "Open",
    avatarColor: "linear-gradient(135deg,#3b82f6,#1d4ed8)",
  },
  {
    id: "3",
    initials: "SA",
    name: "Sam",
    action: "pushed 8 commits to",
    target: "main",
    timeAgo: "1 hr ago",
    avatarColor: "linear-gradient(135deg,#10b981,#059669)",
  },
  {
    id: "4",
    initials: "MR",
    name: "Maria",
    action: "requested review on",
    target: "PR #141",
    timeAgo: "2 hrs ago",
    tag: "Review",
    avatarColor: "linear-gradient(135deg,#f59e0b,#d97706)",
  },
  {
    id: "5",
    initials: "DL",
    name: "Dan",
    action: "closed issue #89 —",
    target: "API timeout",
    timeAgo: "3 hrs ago",
    avatarColor: "linear-gradient(135deg,#f43f5e,#be123c)",
  },
];

export const TEAM_MEMBERS: Member[] = [
  {
    id: "1",
    name: "Alex L.",
    initials: "AL",
    role: "Frontend",
    avatarColor: "linear-gradient(135deg,#8b5cf6,#6d28d9)",
    commits: 342,
    impact: 92,
    score: 98,
  },
  {
    id: "2",
    name: "Sam A.",
    initials: "SA",
    role: "Backend",
    avatarColor: "linear-gradient(135deg,#10b981,#059669)",
    commits: 298,
    impact: 78,
    score: 84,
  },
  {
    id: "3",
    name: "Maria R.",
    initials: "MR",
    role: "Fullstack",
    avatarColor: "linear-gradient(135deg,#f59e0b,#d97706)",
    commits: 261,
    impact: 65,
    score: 76,
  },
  {
    id: "4",
    name: "Jordan K.",
    initials: "JK",
    role: "Frontend",
    avatarColor: "linear-gradient(135deg,#3b82f6,#1d4ed8)",
    commits: 219,
    impact: 55,
    score: 71,
  },
];

export const PULL_REQUESTS: PRItem[] = [
  {
    id: 142,
    title: "Refactor auth middleware",
    author: "Alex L.",
    branch: "feature/auth",
    status: "merged",
    timeAgo: "2 min ago",
  },
  {
    id: 143,
    title: "Dashboard UI improvements",
    author: "Jordan K.",
    branch: "feat/dashboard",
    status: "open",
    timeAgo: "15 min ago",
  },
  {
    id: 141,
    title: "Add Stripe webhook handler",
    author: "Maria R.",
    branch: "feat/payments",
    status: "review",
    timeAgo: "2 hrs ago",
  },
  {
    id: 140,
    title: "Optimize DB queries for reports",
    author: "Sam A.",
    branch: "perf/db",
    status: "open",
    timeAgo: "5 hrs ago",
  },
  {
    id: 139,
    title: "Fix API timeout on /metrics",
    author: "Dan L.",
    branch: "fix/timeout",
    status: "closed",
    timeAgo: "1 day ago",
  },
];
